# Generated by Django 5.2 on 2025-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(related_name='employees', to='tasks.task'),
        ),
    ]
