# Generated by Django 5.2 on 2025-04-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='inventory.inventory')),
            ],
        ),
    ]
