# Generated by Django 5.2 on 2025-04-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('growth_duration', models.IntegerField(default='30', help_text='Durée de croissance en jours')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField()),
                ('yield_amount', models.FloatField(help_text='rendement en tonnes')),
                ('quality_rating', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Eleve')])),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('area', models.FloatField(default=0, help_text='superficie en hectares')),
                ('location', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('area', models.FloatField(default=0, help_text='superficie en hectares')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('seed_quantity', models.FloatField(help_text='Quantité en kg')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farms.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farms.field')),
            ],
        ),
    ]
